<?php

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove the password field when venue admin is creating a customer account. 
 * default check notify user
 * 
 */

function optional_password_form_user_register_form_alter(&$form, &$form_state, &$form_id) {
  global $user;

  if(in_array('venue administrator', $user->roles)) {
    //hide password field
    $form['account']['pass']['#access'] = FALSE;
    $form['account']['pass']['#value']['pass1'] = user_password();
    $form['account']['pass']['#value']['pass2'] = $form['account']['pass']['#value']['pass1'];

    //enable notify by default
    $form['account']['notify']['#default_value'] = TRUE;
    //hide roles and status
    $form['account']['roles']['#access'] = FALSE;
    $form['account']['status']['#access'] = FALSE;
    //make the generate access code required...
    $form['account']['access_code_settings']['access_code']['#required']= TRUE;
  }
}

/**
 * Implements hook_user_presave
 */
  function optional_password_user_presave(&$edit, $account, $category) {
    global $user;
    if(in_array('venue administrator', $user->roles)) {
      if($account ->is_new) {
        $roles = user_roles(TRUE);
        $rid = array_search('customer', $roles);
        if($rid != FALSE) {
          $edit['roles'][$rid] = 1;
        }
      }
    }
  }




