<?php

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove the password field when venue admin is creating an account.
 */

function optional_password_form_user_register_form_alter(&$form, &$form_state, &$form_id) {
  global $user;

  if(in_array('venue administrator', $user->roles)) {
    $form['account']['pass']['#access'] = FALSE;
    $form['account']['pass']['#value']['pass1'] = user_password();
    $form['account']['pass']['#value']['pass2'] = $form['account']['pass']['#value']['pass1'];
  }

  // by default notify user of new account is checked.

  if(in_array('venue administrator', $user->roles)) {     
        $form['account']['notify']['#default_value'] = TRUE;
    }

}
